### ISSUE TITLE
Name of the crate

### ISSUE THREAD

**Issue by jcklie** [Cldfire/nvml-wrapper#11]
Hello,
I am a bit confused about the name of the crate: is it `nvml_wrapper` or `nvml-wrapper`? The repo name has a hyphen, the doc url https://docs.rs/nvml-wrapper/0.4.1/nvml_wrapper/ has both in it and the doc heading is `Crate nvml_wrapper`. I would maybe just add the `extern crate nvml_wrapper as nvml;` and the other imports to the readme example to clarify this.

**Comment by Cldfire** [comment]
Hi! Thanks for opening an issue about this, I agree that it is quite confusing :). It took me a while to figure this particular Rust quirk out when I first started using it as well.

So, here's the rundown: the *package* name is indeed nvml-wrapper, with a hyphen. That is how it will show up on crates.io, how you refer to it in your Cargo.toml, and the official name to refer to the package by. However, due to [a decision](https://github.com/rust-lang/rfcs/blob/master/text/0940-hyphens-considered-harmful.md) that was made a long time ago, hyphens, while being allowed in package names, are not allowed in *crate* names (packages are a Cargo concept while crates are a Rust concept). So, the team decided to auto-convert hyphens in package names to underscores, disallow having two crates with the same name other than the separator ("foo-bar" vs "foo_bar"), and call it a day. It's an annoying papercut that unfortunately will be with us forever more.

That also explains the docs.rs URL: `nvml-wrapper` is referring to the package while `nvml_wrapper` is the path to the crate within rustdoc.

Anyhow, that's the background. I agree that adding the imports to the readme would be a good way to clarify that. I'll take care of it here shortly!

**Comment by Cldfire** [comment]
Added in 523647410fe272eaceb2be8654aea4599906f376.

Thanks again for the suggestion!
