### ISSUE TITLE
Crate errors during build script on macOS

### ISSUE THREAD

**Issue by fifthecho** [Cldfire/nvml-wrapper#8]
``` error[E0601]: `main` function not found in crate `build_script_build` ``` is returned against ``` nvml-wrapper-sys-0.3.0/build.rs ```

**Comment by Cldfire** [comment]
Thank you for filing an issue. I am not going to be able to look into this for a few days at least due to other responsibilities, but I will get to it as soon as possible.

**Comment by Cldfire** [comment]
I just looked into this. Everything is still compiling and running fine with Rust 1.29.1; it sounds like you have run into a different issue caused by trying to compile this crate on macOS, where it is not supported (since NVML does not support macOS).

I will change the issue title and leave it open, however, since the crate shouldn't fail like that on macOS. I'll have to look into what other crates that wrap platform-specific libraries do and determine what the best way to handle this is (I believe winapi is a no-op on platforms other than windows?).

**Comment by Cldfire** [comment]
Fixed in c8a3083277f030df00cb8ae32f0df4e9551418e4. I will leave this issue open until the fix is released on crates.io (not sure when that will be) so that anyone else who runs in to this can see it.

**Comment by Cldfire** [comment]
The fix was made live as part of `0.4.1`.
